# permissions for end users to view dataproducts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataproduct-viewer-role
rules:
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - dataproducts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - dataproducts/status
  verbs:
  - get
