# permissions for end users to view inputports3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inputports3-viewer-role
rules:
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - inputports3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - inputports3s/status
  verbs:
  - get
