# permissions for end users to edit outputports3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: outputports3-editor-role
rules:
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - outputports3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - outputports3s/status
  verbs:
  - get
