# permissions for end users to view outputports3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: outputports3-viewer-role
rules:
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - outputports3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datamesh.demeulder.us
  resources:
  - outputports3s/status
  verbs:
  - get
