apiVersion: datamesh.demeulder.us/v1
kind: DataProduct
metadata:
  name: sales-analytics
spec:
  image: busybox
  cronexpr: "0 0 0 0 1"
  inputPorts:
  - invoices
  - products
  outputPorts:
  - products-analytics
  size: 1
